/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace IComplianceModule {
      
    export type HashedAttestationStruct = {kycAttestationHash: BytesLike, attestationExpiry: BigNumberish}

    export type HashedAttestationStructOutput = [kycAttestationHash: string, attestationExpiry: bigint] & {kycAttestationHash: string, attestationExpiry: bigint }
  

    export type ComplianceMetadataStruct = {lei: BytesLike, isin: BytesLike, cfi: BytesLike, jurisdiction: BytesLike, investorCategory: BigNumberish, kycAttestationHash: BytesLike, attestationExpiry: BigNumberish, customRestrictionFlags: BytesLike}

    export type ComplianceMetadataStructOutput = [lei: string, isin: string, cfi: string, jurisdiction: string, investorCategory: bigint, kycAttestationHash: string, attestationExpiry: bigint, customRestrictionFlags: string] & {lei: string, isin: string, cfi: string, jurisdiction: string, investorCategory: bigint, kycAttestationHash: string, attestationExpiry: bigint, customRestrictionFlags: string }
  
    }

  export interface ComplianceModuleInterface extends Interface {
    getFunction(nameOrSignature: "authorizeIssuer" | "authorizedIssuers" | "getHashedAttestation" | "getMetadata" | "isEligible" | "owner" | "renounceOwnership" | "revokeAttestation" | "storeAttestation" | "storeAttestationHash" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AttestationHashStored" | "AttestationRevoked" | "AttestationStored" | "IssuerAuthorized" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'authorizeIssuer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'authorizedIssuers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getHashedAttestation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getMetadata', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isEligible', values: [AddressLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'revokeAttestation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'storeAttestation', values: [AddressLike, IComplianceModule.ComplianceMetadataStruct]): string;
encodeFunctionData(functionFragment: 'storeAttestationHash', values: [AddressLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'authorizeIssuer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedIssuers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getHashedAttestation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMetadata', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isEligible', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeAttestation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'storeAttestation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'storeAttestationHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace AttestationHashStoredEvent {
      export type InputTuple = [holder: AddressLike, kycHash: BytesLike];
      export type OutputTuple = [holder: string, kycHash: string];
      export interface OutputObject {holder: string, kycHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AttestationRevokedEvent {
      export type InputTuple = [holder: AddressLike];
      export type OutputTuple = [holder: string];
      export interface OutputObject {holder: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AttestationStoredEvent {
      export type InputTuple = [holder: AddressLike, kycHash: BytesLike];
      export type OutputTuple = [holder: string, kycHash: string];
      export interface OutputObject {holder: string, kycHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IssuerAuthorizedEvent {
      export type InputTuple = [issuer: AddressLike];
      export type OutputTuple = [issuer: string];
      export interface OutputObject {issuer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ComplianceModule extends BaseContract {
    
    connect(runner?: ContractRunner | null): ComplianceModule;
    waitForDeployment(): Promise<this>;

    interface: ComplianceModuleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    authorizeIssuer: TypedContractMethod<
      [issuer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    authorizedIssuers: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    getHashedAttestation: TypedContractMethod<
      [holder: AddressLike, ],
      [IComplianceModule.HashedAttestationStructOutput],
      'view'
    >
    

    
    getMetadata: TypedContractMethod<
      [holder: AddressLike, ],
      [IComplianceModule.ComplianceMetadataStructOutput],
      'view'
    >
    

    
    isEligible: TypedContractMethod<
      [holder: AddressLike, requiredJurisdiction: BytesLike, requiredCategory: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    revokeAttestation: TypedContractMethod<
      [holder: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    storeAttestation: TypedContractMethod<
      [holder: AddressLike, meta: IComplianceModule.ComplianceMetadataStruct, ],
      [void],
      'nonpayable'
    >
    

    
    storeAttestationHash: TypedContractMethod<
      [holder: AddressLike, kycAttestationHash: BytesLike, attestationExpiry: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'authorizeIssuer'): TypedContractMethod<
      [issuer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'authorizedIssuers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getHashedAttestation'): TypedContractMethod<
      [holder: AddressLike, ],
      [IComplianceModule.HashedAttestationStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getMetadata'): TypedContractMethod<
      [holder: AddressLike, ],
      [IComplianceModule.ComplianceMetadataStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isEligible'): TypedContractMethod<
      [holder: AddressLike, requiredJurisdiction: BytesLike, requiredCategory: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeAttestation'): TypedContractMethod<
      [holder: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'storeAttestation'): TypedContractMethod<
      [holder: AddressLike, meta: IComplianceModule.ComplianceMetadataStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'storeAttestationHash'): TypedContractMethod<
      [holder: AddressLike, kycAttestationHash: BytesLike, attestationExpiry: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AttestationHashStored'): TypedContractEvent<AttestationHashStoredEvent.InputTuple, AttestationHashStoredEvent.OutputTuple, AttestationHashStoredEvent.OutputObject>;
getEvent(key: 'AttestationRevoked'): TypedContractEvent<AttestationRevokedEvent.InputTuple, AttestationRevokedEvent.OutputTuple, AttestationRevokedEvent.OutputObject>;
getEvent(key: 'AttestationStored'): TypedContractEvent<AttestationStoredEvent.InputTuple, AttestationStoredEvent.OutputTuple, AttestationStoredEvent.OutputObject>;
getEvent(key: 'IssuerAuthorized'): TypedContractEvent<IssuerAuthorizedEvent.InputTuple, IssuerAuthorizedEvent.OutputTuple, IssuerAuthorizedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'AttestationHashStored(address,bytes32)': TypedContractEvent<AttestationHashStoredEvent.InputTuple, AttestationHashStoredEvent.OutputTuple, AttestationHashStoredEvent.OutputObject>;
      AttestationHashStored: TypedContractEvent<AttestationHashStoredEvent.InputTuple, AttestationHashStoredEvent.OutputTuple, AttestationHashStoredEvent.OutputObject>;
    

      'AttestationRevoked(address)': TypedContractEvent<AttestationRevokedEvent.InputTuple, AttestationRevokedEvent.OutputTuple, AttestationRevokedEvent.OutputObject>;
      AttestationRevoked: TypedContractEvent<AttestationRevokedEvent.InputTuple, AttestationRevokedEvent.OutputTuple, AttestationRevokedEvent.OutputObject>;
    

      'AttestationStored(address,bytes32)': TypedContractEvent<AttestationStoredEvent.InputTuple, AttestationStoredEvent.OutputTuple, AttestationStoredEvent.OutputObject>;
      AttestationStored: TypedContractEvent<AttestationStoredEvent.InputTuple, AttestationStoredEvent.OutputTuple, AttestationStoredEvent.OutputObject>;
    

      'IssuerAuthorized(address)': TypedContractEvent<IssuerAuthorizedEvent.InputTuple, IssuerAuthorizedEvent.OutputTuple, IssuerAuthorizedEvent.OutputObject>;
      IssuerAuthorized: TypedContractEvent<IssuerAuthorizedEvent.InputTuple, IssuerAuthorizedEvent.OutputTuple, IssuerAuthorizedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }