/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface DvPSettlementManagerInterface extends Interface {
    getFunction(nameOrSignature: "abort" | "commit" | "complianceModule" | "createDvP" | "finalise" | "jurisdiction" | "owner" | "renounceOwnership" | "requiredCategory" | "settlements" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DvPAborted" | "DvPCreated" | "DvPFinalised" | "OwnershipTransferred" | "PartyCommitted"): EventFragment;

    encodeFunctionData(functionFragment: 'abort', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'commit', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'complianceModule', values?: undefined): string;
encodeFunctionData(functionFragment: 'createDvP', values: [AddressLike, BigNumberish, AddressLike, BigNumberish, AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'finalise', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'jurisdiction', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'requiredCategory', values?: undefined): string;
encodeFunctionData(functionFragment: 'settlements', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'abort', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'complianceModule', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createDvP', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalise', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'jurisdiction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requiredCategory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settlements', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace DvPAbortedEvent {
      export type InputTuple = [settlementId: BytesLike];
      export type OutputTuple = [settlementId: string];
      export interface OutputObject {settlementId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DvPCreatedEvent {
      export type InputTuple = [settlementId: BytesLike, buyer: AddressLike, seller: AddressLike, assetAmount: BigNumberish, paymentAmount: BigNumberish];
      export type OutputTuple = [settlementId: string, buyer: string, seller: string, assetAmount: bigint, paymentAmount: bigint];
      export interface OutputObject {settlementId: string, buyer: string, seller: string, assetAmount: bigint, paymentAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DvPFinalisedEvent {
      export type InputTuple = [settlementId: BytesLike];
      export type OutputTuple = [settlementId: string];
      export interface OutputObject {settlementId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PartyCommittedEvent {
      export type InputTuple = [settlementId: BytesLike, party: AddressLike];
      export type OutputTuple = [settlementId: string, party: string];
      export interface OutputObject {settlementId: string, party: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface DvPSettlementManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): DvPSettlementManager;
    waitForDeployment(): Promise<this>;

    interface: DvPSettlementManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    abort: TypedContractMethod<
      [settlementId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    commit: TypedContractMethod<
      [settlementId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    complianceModule: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    createDvP: TypedContractMethod<
      [assetToken: AddressLike, assetAmount: BigNumberish, paymentToken: AddressLike, paymentAmount: BigNumberish, buyer: AddressLike, seller: AddressLike, expiryBlock: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    finalise: TypedContractMethod<
      [settlementId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    jurisdiction: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    requiredCategory: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    settlements: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, bigint, string, bigint, string, string, bigint, string, boolean, boolean, bigint] & {assetToken: string, assetAmount: bigint, paymentToken: string, paymentAmount: bigint, buyer: string, seller: string, expiryBlock: bigint, holdId: string, buyerCommitted: boolean, sellerCommitted: boolean, status: bigint }],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'abort'): TypedContractMethod<
      [settlementId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'commit'): TypedContractMethod<
      [settlementId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'complianceModule'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createDvP'): TypedContractMethod<
      [assetToken: AddressLike, assetAmount: BigNumberish, paymentToken: AddressLike, paymentAmount: BigNumberish, buyer: AddressLike, seller: AddressLike, expiryBlock: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalise'): TypedContractMethod<
      [settlementId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'jurisdiction'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requiredCategory'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'settlements'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, bigint, string, bigint, string, string, bigint, string, boolean, boolean, bigint] & {assetToken: string, assetAmount: bigint, paymentToken: string, paymentAmount: bigint, buyer: string, seller: string, expiryBlock: bigint, holdId: string, buyerCommitted: boolean, sellerCommitted: boolean, status: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DvPAborted'): TypedContractEvent<DvPAbortedEvent.InputTuple, DvPAbortedEvent.OutputTuple, DvPAbortedEvent.OutputObject>;
getEvent(key: 'DvPCreated'): TypedContractEvent<DvPCreatedEvent.InputTuple, DvPCreatedEvent.OutputTuple, DvPCreatedEvent.OutputObject>;
getEvent(key: 'DvPFinalised'): TypedContractEvent<DvPFinalisedEvent.InputTuple, DvPFinalisedEvent.OutputTuple, DvPFinalisedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PartyCommitted'): TypedContractEvent<PartyCommittedEvent.InputTuple, PartyCommittedEvent.OutputTuple, PartyCommittedEvent.OutputObject>;

    filters: {
      
      'DvPAborted(bytes32)': TypedContractEvent<DvPAbortedEvent.InputTuple, DvPAbortedEvent.OutputTuple, DvPAbortedEvent.OutputObject>;
      DvPAborted: TypedContractEvent<DvPAbortedEvent.InputTuple, DvPAbortedEvent.OutputTuple, DvPAbortedEvent.OutputObject>;
    

      'DvPCreated(bytes32,address,address,uint256,uint256)': TypedContractEvent<DvPCreatedEvent.InputTuple, DvPCreatedEvent.OutputTuple, DvPCreatedEvent.OutputObject>;
      DvPCreated: TypedContractEvent<DvPCreatedEvent.InputTuple, DvPCreatedEvent.OutputTuple, DvPCreatedEvent.OutputObject>;
    

      'DvPFinalised(bytes32)': TypedContractEvent<DvPFinalisedEvent.InputTuple, DvPFinalisedEvent.OutputTuple, DvPFinalisedEvent.OutputObject>;
      DvPFinalised: TypedContractEvent<DvPFinalisedEvent.InputTuple, DvPFinalisedEvent.OutputTuple, DvPFinalisedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PartyCommitted(bytes32,address)': TypedContractEvent<PartyCommittedEvent.InputTuple, PartyCommittedEvent.OutputTuple, PartyCommittedEvent.OutputObject>;
      PartyCommitted: TypedContractEvent<PartyCommittedEvent.InputTuple, PartyCommittedEvent.OutputTuple, PartyCommittedEvent.OutputObject>;
    
    };
  }