/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface HoldTokenInterface extends Interface {
    getFunction(nameOrSignature: "allowance" | "approve" | "availableBalanceOf" | "balanceOf" | "createHold" | "decimals" | "executeHold" | "holds" | "lockedBalanceOf" | "name" | "owner" | "reclaimHold" | "releaseHold" | "renounceOwnership" | "symbol" | "totalSupply" | "transfer" | "transferFrom" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "HoldCreated" | "HoldExecuted" | "HoldReclaimed" | "HoldReleased" | "OwnershipTransferred" | "Transfer"): EventFragment;

    encodeFunctionData(functionFragment: 'allowance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'availableBalanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'createHold', values: [BytesLike, AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeHold', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'holds', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'lockedBalanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'reclaimHold', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'releaseHold', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transfer', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'allowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'availableBalanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createHold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeHold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'holds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockedBalanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reclaimHold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseHold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, spender: AddressLike, value: BigNumberish];
      export type OutputTuple = [owner: string, spender: string, value: bigint];
      export interface OutputObject {owner: string, spender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace HoldCreatedEvent {
      export type InputTuple = [holdId: BytesLike, holder: AddressLike, notary: AddressLike, amount: BigNumberish, expiry: BigNumberish];
      export type OutputTuple = [holdId: string, holder: string, notary: string, amount: bigint, expiry: bigint];
      export interface OutputObject {holdId: string, holder: string, notary: string, amount: bigint, expiry: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace HoldExecutedEvent {
      export type InputTuple = [holdId: BytesLike, to: AddressLike];
      export type OutputTuple = [holdId: string, to: string];
      export interface OutputObject {holdId: string, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace HoldReclaimedEvent {
      export type InputTuple = [holdId: BytesLike];
      export type OutputTuple = [holdId: string];
      export interface OutputObject {holdId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace HoldReleasedEvent {
      export type InputTuple = [holdId: BytesLike];
      export type OutputTuple = [holdId: string];
      export interface OutputObject {holdId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, value: BigNumberish];
      export type OutputTuple = [from: string, to: string, value: bigint];
      export interface OutputObject {from: string, to: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface HoldToken extends BaseContract {
    
    connect(runner?: ContractRunner | null): HoldToken;
    waitForDeployment(): Promise<this>;

    interface: HoldTokenInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    allowance: TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    availableBalanceOf: TypedContractMethod<
      [holder: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    createHold: TypedContractMethod<
      [holdId: BytesLike, holder: AddressLike, notary: AddressLike, amount: BigNumberish, expiry: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    decimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    executeHold: TypedContractMethod<
      [holdId: BytesLike, to: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    holds: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, bigint] & {holder: string, notary: string, amount: bigint, expiry: bigint, status: bigint }],
      'view'
    >
    

    
    lockedBalanceOf: TypedContractMethod<
      [holder: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    reclaimHold: TypedContractMethod<
      [holdId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    releaseHold: TypedContractMethod<
      [holdId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transfer: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'allowance'): TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'availableBalanceOf'): TypedContractMethod<
      [holder: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createHold'): TypedContractMethod<
      [holdId: BytesLike, holder: AddressLike, notary: AddressLike, amount: BigNumberish, expiry: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'executeHold'): TypedContractMethod<
      [holdId: BytesLike, to: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'holds'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, bigint] & {holder: string, notary: string, amount: bigint, expiry: bigint, status: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'lockedBalanceOf'): TypedContractMethod<
      [holder: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'reclaimHold'): TypedContractMethod<
      [holdId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseHold'): TypedContractMethod<
      [holdId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'HoldCreated'): TypedContractEvent<HoldCreatedEvent.InputTuple, HoldCreatedEvent.OutputTuple, HoldCreatedEvent.OutputObject>;
getEvent(key: 'HoldExecuted'): TypedContractEvent<HoldExecutedEvent.InputTuple, HoldExecutedEvent.OutputTuple, HoldExecutedEvent.OutputObject>;
getEvent(key: 'HoldReclaimed'): TypedContractEvent<HoldReclaimedEvent.InputTuple, HoldReclaimedEvent.OutputTuple, HoldReclaimedEvent.OutputObject>;
getEvent(key: 'HoldReleased'): TypedContractEvent<HoldReleasedEvent.InputTuple, HoldReleasedEvent.OutputTuple, HoldReleasedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'HoldCreated(bytes32,address,address,uint256,uint256)': TypedContractEvent<HoldCreatedEvent.InputTuple, HoldCreatedEvent.OutputTuple, HoldCreatedEvent.OutputObject>;
      HoldCreated: TypedContractEvent<HoldCreatedEvent.InputTuple, HoldCreatedEvent.OutputTuple, HoldCreatedEvent.OutputObject>;
    

      'HoldExecuted(bytes32,address)': TypedContractEvent<HoldExecutedEvent.InputTuple, HoldExecutedEvent.OutputTuple, HoldExecutedEvent.OutputObject>;
      HoldExecuted: TypedContractEvent<HoldExecutedEvent.InputTuple, HoldExecutedEvent.OutputTuple, HoldExecutedEvent.OutputObject>;
    

      'HoldReclaimed(bytes32)': TypedContractEvent<HoldReclaimedEvent.InputTuple, HoldReclaimedEvent.OutputTuple, HoldReclaimedEvent.OutputObject>;
      HoldReclaimed: TypedContractEvent<HoldReclaimedEvent.InputTuple, HoldReclaimedEvent.OutputTuple, HoldReclaimedEvent.OutputObject>;
    

      'HoldReleased(bytes32)': TypedContractEvent<HoldReleasedEvent.InputTuple, HoldReleasedEvent.OutputTuple, HoldReleasedEvent.OutputObject>;
      HoldReleased: TypedContractEvent<HoldReleasedEvent.InputTuple, HoldReleasedEvent.OutputTuple, HoldReleasedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    
    };
  }